spring.application.name=backend

# PostgreSQL / Supabase Session Pooler
spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.mzpglzxrqnltgutdefdi
spring.datasource.password=AnkurSamad@0801


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080